version: '3'
services:
    vue:
        build: .
        volumes:
            - ./app:/app
        ports:
            - '8080:8080'
            - '5000:5000'
            - '5001:5001'
        stdin_open: true
        tty: true
